### ISSUE TITLE
传统应用部署测试失败

### ISSUE THREAD

**Issue by kunzhijia** [openpitrix/openpitrix#1013]
我使用docker compose 安装的openpitrix，测试WordPress的vm安装方式，测试部署到青云，但是报错，报错信息如下：

内部错误: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9114: connect: connection refused"

请问能帮忙解答下吗，是否存在配置问题

**Comment by zheng1** [comment]
检查下 openpitrix-pilot-service 是否配置成功

**Comment by chilianyi** [comment]
Pilot 服务 http 协议的端口为 9114 

需要将端口 9114 暴露给外部访问（需要端口转发和防火墙放行该端口，确保流量能够通过该端口），可以参考：https://openpitrix.io/docs/v0.4/zh-CN/appendix/qingcloud-manipulation

**Comment by kunzhijia** [comment]
openpitrix-pilot-service是部署在自己电脑的，是否这种方式不行

**Comment by chilianyi** [comment]
参考下：https://segmentfault.com/a/1190000011827338

应该可以把本地服务暴漏到公网，这样 青云主机就能够访问了。

**Comment by kunzhijia** [comment]
我已经在阿里云部署了一套，且也确认基于ip:9114是可以访问到请求，但是依旧是同一个错误

内部错误: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:9114: connect: connection refused"

**Comment by kunzhijia** [comment]
是否在启动make 指令前，需要对pilot的配置文件进行配置

**Comment by zheng1** [comment]
> 是否在启动make 指令前，需要对pilot的配置文件进行配置

docker-compose版本也需要修改配置文件，具体操作如下：
```bash
# 下载配置文件
make compose-get-global-config

# 修改 pilot 块中的 ip 和 port
vim global_config.yaml

# 更新配置文件
make compose-put-global-config
```

**Comment by kunzhijia** [comment]
感谢，已经跑通
