### ISSUE TITLE
Error: validation failed: [unable to recognize "": no matches for kind "Deployment"

### ISSUE THREAD

**Issue by zhangchunsheng** [openpitrix/openpitrix#1041]
helm install . -n openpitrix --namespace openpitrix-io-system
```
Error: validation failed: [unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "apps/v1beta2"]
```

kubectl version
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

helm version
```
Client: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.10", GitCommit:"bceca24a91639f045f22ab0f41e47589a932cf5e", GitTreeState:"clean"}
```

**Comment by escoffier** [comment]
Deployment in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API versions is no longer served since Kubernetes v1.16

[https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/)

**Comment by zheng1** [comment]
It is highly recommended that you use the KubeSphere App Store. OpenPitrix is now deeply integrated with KubeSphere. The legacy code will no longer be maintained.

**Comment by zhangchunsheng** [comment]
> It is highly recommended that you use the KubeSphere App Store. OpenPitrix is now deeply integrated with KubeSphere. The legacy code will no longer be maintained.

ok

**Comment by zhangchunsheng** [comment]
> It is highly recommended that you use the KubeSphere App Store. OpenPitrix is now deeply integrated with KubeSphere. The legacy code will no longer be maintained.

ok
