### ISSUE TITLE
项目已经不维护了吗

### ISSUE THREAD

**Issue by lgy1027** [openpitrix/openpitrix#1056]
该项目不独立维护了吗，无法加入slack，请问有社区吗，还是说在kubesphere社区

**Comment by zheng1** [comment]
已经合并入 KubeSphere 主干代码中，近期会更新一个基于 KubeSphere 的版本

**Comment by yangyuw** [comment]
> 已经合并入 KubeSphere 主干代码中，近期会更新一个基于 KubeSphere 的版本

不会有单独的all in one版本了吗？
