### ISSUE TITLE
Displaying error when accessing swagger page

### ISSUE THREAD

**Issue by calvinyv** [openpitrix/openpitrix#127]
1. Setup dev env through docker compose
2. Access http://127.0.0.1:9100/swagger-ui 
3. At the bottom of the page, it prompt error section, click that link and get msg as:
"Can't read from file /sw…ger-ui/app.swagger.json"

![snip20180201_1](https://user-images.githubusercontent.com/28883416/35659405-14169aae-0741-11e8-9886-ae3fe2191a38.png)

**Comment by chai2010** [comment]
we should disable the validation.

refs:

- https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
- https://github.com/swagger-api/swagger-ui/issues/2948
