### ISSUE TITLE
I think we can use gorm to interacting with database

### ISSUE THREAD

**Issue by Hevienz** [openpitrix/openpitrix#138]
- The document of gorm is clear.
- Gorm will do auto migration when the structure of table is changed.
- Base model definition in gorm.Model, including fields ID, CreatedAt, UpdatedAt, DeletedAt, you could embed it in your model, or only write those fields you want.
- Gorm use chainable API, *gorm.DB is the bridge of chains, for each chain API, it will create a new relation.

**Comment by rayzhou2017** [comment]
Please make a decision about this one.

**Comment by chai2010** [comment]
Full-Featured is not the key problem for orm in openpitrix.

less is more for me, std database/sql is first choice for me:

1. it is std pkg, and no 3rd depends.
2. no bug

or just copy a little orm code for OpenPitrix.

if we choose a complex/large 3rd package, 
we must have ability to fix any bug maybe in 3rd pkg.

**Comment by chilianyi** [comment]
Gorp
```
count, err := dbmap.SelectInt("select count(*) from foo where blah=?", blahVal)
```
Gorm
```
db.Model(&User{}).Where("blah = ?", blahVal).Count(&count)
```

Gorp is easier to write than gorm because we just write sql here, no need to read doc. so I prefer gorp.

**Comment by zheng1** [comment]
I tend to use https://github.com/gocraft/dbr for the following reasons:
- Qingstor team has used this library **in production**, the stability is trustworthy
- This library code is small, the structure is very simple, there is no third-party dependence, we can maintain it later.

There are some important points that need to be clarified:
- Our database schema and init code should not be blend with service-related code

**Comment by chai2010** [comment]
all i know, the dbstore is the simplest sqlite orm created by rsc:
https://github.com/rsc/dbstore/blob/master/db.go

it has only one go file. IMO, the mysql support should be similar.

**Comment by chilianyi** [comment]
Now, we have four choices: 
* https://github.com/jinzhu/gorm
* https://github.com/go-gorp/gorp
* https://github.com/gocraft/dbr
* https://github.com/rsc/dbstore/blob/master/db.go(This one need us to do more works)

I think each of them is able to satisfied with our requirements, each of them is easy to use.
Our requirements of sql are simple, what we need is just CRUD. 

As zheng1 said above, dbr has no third-party dependence, maybe we could try this one.

**Comment by martinyunify** [comment]
#141 
I need to implement a schema validation program to check if the db schema is compatible with data model defined in app. So could you please make a decision about this issue? Thanks!

**Comment by chilianyi** [comment]
[Dbr](https://github.com/gocraft/dbr) is our final  decision.
