### ISSUE TITLE
OpenPitrix 0.1 Feature List 

### ISSUE THREAD

**Issue by lijiangsheng1** [openpitrix/openpitrix#207]
<table class="tg">
  <tr>
    <th class="tg-yw4l">Service</th>
    <th class="tg-yw4l">Sub components</th>
    <th class="tg-yw4l">Features</th>
  </tr>
  <tr>
    <td class="tg-yw4l" rowspan="13">Runtime</td>
    <td class="tg-yw4l" rowspan="8">QingCloud Support</td>
    <td class="tg-yw4l">Create (applications)</td>
  </tr>
  <tr>
    <td class="tg-yw4l">Delete</td>
  </tr>
  <tr>
    <td class="tg-yw4l">Shutdown, Start</td>
  </tr>
  <tr>
    <td class="tg-yw4l">Create VPC,Subnet,Vip manual </td>
  </tr>
  <tr>
    <td class="tg-yw4l" rowspan="3">Kubernetes Support</td>
    <td class="tg-yw4l">Helm create </td>
  </tr>
  <tr>
    <td class="tg-us36">(Helm)Delete，restore,Remove completely</td>
  </tr>
  <tr>
    <td class="tg-us36">(Helm)update Environment variables</td>
  </tr>
  <tr>
    <td class="tg-us36">OpenStack Support </td>
    <td class="tg-us36">N/A</td>
  </tr>
  <tr>
    <td class="tg-us36">AWS Support </td>
    <td class="tg-us36">N/A</td>
  </tr>
 <tr>
    <td class="tg-yw4l" colspan="2" rowspan="3">Repo</td>
    <td class="tg-yw4l">Support read only protocol like: http/https/s3 etc.</td>
  </tr>
  <tr>
    <td class="tg-yw4l">Support Helm format and customize about packages.</td>
  </tr>
  <tr>
    <td class="tg-yw4l">package checksum</td>
  </tr>
  <tr>
    <td class="tg-yw4l" colspan="2" rowspan="4">App</td>
    <td class="tg-yw4l">Application and it's version information auto indexing.</td>
  </tr>
  <tr>
    <td class="tg-yw4l"></td>
  </tr>
  <tr>
    <td class="tg-yw4l"></td>
  </tr>
  <tr>
    <td class="tg-yw4l"></td>
  </tr>
  <tr>
    <td class="tg-yw4l" colspan="2" rowspan="2">Metadata</td>
    <td class="tg-yw4l">Configuration update.</td>
  </tr>
  <tr>
    <td class="tg-yw4l"></td>
  </tr>
  <tr>
    <td class="tg-yw4l" colspan="2" rowspan="2">Others </td>
    <td class="tg-yw4l">CLI and Graphical user interface both of them ready.</td>
  </tr>
  <tr>
    <td class="tg-yw4l">Kubernetes deployment.</td>
  </tr>
</table>

**Comment by calvinyv** [comment]
what about pilot, fg and drone support? part of KVM(qingcloud) runtime?

**Comment by chilianyi** [comment]
Finished.
