### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by tanglei528** [openpitrix/openpitrix#312]
make build

Error when performing this step:
...
@docker build -t openpitrix/openpitrix:metadata -f ./Dockerfile.metadata .
...

And the error message:
Step 1/7 : FROM openpitrix/openpitrix-builder as builder
Error parsing reference: "openpitrix/openpitrix-builder as builder" is not a valid repository/tag: invalid reference format
make: *** [build] Error 1

My docker version:
# docker --version
Docker version 1.13.1, build 774336d/1.13.1

**Comment by chilianyi** [comment]
"as builder" is a new docker feature. 
You need to upgrade your docker version.

**Comment by tanglei528** [comment]
Yeah, it worked.
