### ISSUE TITLE
provide custom protobuf plugin to generate small rest client

### ISSUE THREAD

**Issue by chai2010** [openpitrix/openpitrix#519]
to replace swagger-go plugin

**Comment by zheng1** [comment]
optional: https://github.com/yunify/snips/

**Comment by chai2010** [comment]
The OpenPitrix use grpc-gateway to generate rest service,
and the rest api is defined in [protobuf file](https://github.com/openpitrix/openpitrix/blob/master/api/app.proto#L205):

```protobuf
service AppManager {
	rpc CreateApp (CreateAppRequest) returns (CreateAppResponse) {
		option (grpc.gateway.protoc_gen_swagger.options.openapiv2_operation) = {
			summary: "create app"
		};
		option (google.api.http) = {
			post: "/v1/apps"
			body: "*"
		};
	}
}
```

i plan to generate the rest client from same protobuf file.
So the rest client use the same pbtype as grpc.

The snip depends on swagger file, and it will generate
new request and reponse type (different from grpc type).
