### ISSUE TITLE
Runtime Plugin

### ISSUE THREAD

**Issue by shadabpathan143** [openpitrix/openpitrix#545]
How can we register runtime (Cloud Provider) OpenPitrix?
what are the steps or process to complete the above statement?
Is there any source code available, from which we can take reference for the same?

**Comment by Hevienz** [comment]
You can find runtime provider interface in `https://github.com/openpitrix/openpitrix/blob/master/pkg/plugins/plugin.go`.
And you need to implement this interface.

I will explain these method below:

* ParseClusterConf(versionId, runtimeId, conf string) (*models.ClusterWrapper, error)
Conf comes with the cluster definition from web ui，it just like this:
```json
{
    "cluster": {
        "name": "ELK",
        "description": "The description of the ELK service",
        "subnet": "vxnet-dkdu5u0",
        "es_node": {
            "cpu": 2,
            "memory": 4096,
            "count": 3,
            "instance_class": 1,
            "volume_size": 10
        },
        "kbn_node": {
            "cpu": 2,
            "memory": 4096,
            "count": 1,
            "instance_class": 1,
            "volume_size": 10
        },
        "lst_node": {
            "cpu": 2,
            "memory": 4096,
            "count": 1,
            "instance_class": 1,
            "volume_size": 10
        }
    },
    "env": {
        "es_node": {
            "action_destructive_requires_name": "true",
            "indices_fielddata_cache_size": "90%",
            "logstash_node_ip": "",
            "discovery_zen_no_master_block": "write",
            "gateway_recover_after_time": "5m",
            "http_cors_enabled": "true",
            "http_cors_allow_origin": "*",
            "indices_queries_cache_size": "10%",
            "indices_memory_index_buffer_size": "10%",
            "indices_requests_cache_size": "2%",
            "script_inline": "true",
            "script_stored": "true",
            "script_file": "false",
            "script_aggs": "true",
            "script_search": "true",
            "script_update": "true",
            "remote_ext_dict": "",
            "remote_ext_stopwords": ""
        },
        "lst_node": {
            "input_conf_content": "http { port => 9700 }",
            "filter_conf_content": "",
            "output_conf_content": "",
            "output_es_content": "",
            "gemfile_append_content": ""
        }
    }
}
```

This method generate what cluster is represented in openpitrix finally.

* SplitJobIntoTasks(job *models.Job) (*models.TaskLayer, error)
This method convert job to hierarchical tasks.

* HandleSubtask(task *models.Task) error
This method do the true task.

* WaitSubtask(task *models.Task, timeout time.Duration, waitInterval time.Duration) error
This method wait for task finish.

* DescribeSubnets(ctx context.Context, req *pb.DescribeSubnetsRequest) (*pb.DescribeSubnetsResponse, error)
This method is used for tell user her subnet list, and then she can choice one from them.

* CheckResource(ctx context.Context, clusterWrapper *models.ClusterWrapper) error
This method is used for check wether resources is enough for create cluster.

* DescribeVpc(runtimeId, vpcId string) (*models.Vpc, error)
This method is used for tell user her vpc list, and then she can choice one from them.

* ValidateCredential(url, credential, zone string) error
This method is used for conform credential is correct for accessing the runtime.

* DescribeRuntimeProviderZones(url, credential string) ([]string, error)
This method is used for tell user zone list, and then she can choice one from them.

* UpdateClusterStatus(job *models.Job) error
This method is used for update cluster status when job is finished.

You can find examples in `https://github.com/openpitrix/openpitrix/tree/master/pkg/plugins`,
aws, qingcloud may give you inspiration.

**Comment by shadabpathan143** [comment]
Thank you Hevienz for your precious time.
again I wanted to clear my doubt,
like AWS, QingCloud have made their plugins

https://github.com/openpitrix/openpitrix/tree/master/pkg/plugins

should I too have to make such plugins and request to OpenPitrix for providing support to the cloud like e.g ( Alibaba, Baidu )??

**Comment by Hevienz** [comment]
We will provide the plugin for Aliyun before  the end of September.

We have no plan for Baidu. 

Pr is welcome for implement these plugins.

**Comment by shadabpathan143** [comment]
Ok,
Thank you!
