### ISSUE TITLE
DevOps Env

### ISSUE THREAD

**Issue by sp-click2cloud** [openpitrix/openpitrix#548]
"Jenkins with Blue Ocean plugin and deploy it on Kubernetes, also continuously deploy OpenPitrix on the Kubernetes cluster."
Can you please provide YAML file for above?

**Comment by rayzhou2017** [comment]
The link is fixed. I also changed the file name. You can get it from https://github.com/openpitrix/openpitrix/blob/master/deploy/devops/jenkins-k8s.yaml

**Comment by sp-click2cloud** [comment]
Thank you!
