### ISSUE TITLE
Etcd container starting after frontgate container will cause StartCluster job to fail

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/openpitrix#593]
When CreateCluster, we define the dependencies in system config, so etcd container will start before frontgate container.

When StartCluster(The cluster is in stop status and frontgate cluster is also in stop status), etcd container may start after frontgate container, which leads RegisterMetadata task to fail. The job will fail too.

**Comment by chai2010** [comment]
frontgate service should provides ping metadata backend server api.
