### ISSUE TITLE
Frontgate not reconnect to Pilot automatic when Pilot restart

### ISSUE THREAD

**Issue by chilianyi** [openpitrix/openpitrix#609]
My Pilot restart many times, while Frontgate still has the connection. 
![screenshot from 2018-09-06 16-47-59](https://user-images.githubusercontent.com/5917832/45166721-402f1c80-b22a-11e8-99f7-32b60f18bb79.png)
Frontgate has not been realized that the connection has been disconnected.
Maybe need keepalive?

**Comment by chai2010** [comment]
frontgate need use ping the check pilot status, if the ping failed, frontgate should close the pilot grpc client.

**Comment by chilianyi** [comment]
Thanks, your #611 will solve this problem.
