### ISSUE TITLE
Login failed by all_in_one deployment

### ISSUE THREAD

**Issue by cxyfreedom** [openpitrix/openpitrix#821]
## Description

Login with username and password failed

## Install Mode

All-in-One

## Snapshot

docker-compose ps
![image](https://user-images.githubusercontent.com/8132652/51155473-971cc080-18b2-11e9-9ec2-faade1784992.png)

error
![image](https://user-images.githubusercontent.com/8132652/51155504-ab60bd80-18b2-11e9-94ae-f16259feea1a.png)

**Comment by xidianzhouya** [comment]
I also met this error when login with admin@op.com/passw0rd?
How did you solve this problem?

**Comment by xidianzhouya** [comment]
Thanks

**Comment by chai2010** [comment]
@xidianzhouya 你好，目前iam（账号和全新）模块还在开发过程中。出现该错误可能的原因是有部分代码已经使用了该服务，但是docker-compose配置文件还没有包含这个服务。抱歉给你带来了困扰。

如果想测试最新的iam模块，可以先合并 https://github.com/openpitrix/openpitrix/pull/827 这个补丁，然后在项目根目录执行 `make build & make compose-up` , 然后打开 http://127.0.0.1/8000 登陆界面.

更新信息可以参考这里：
https://docs.openpitrix.io/home
