### ISSUE TITLE
hyperpitrix service host Unreachable

### ISSUE THREAD

**Issue by pengcong06** [openpitrix/openpitrix#942]
deploy service separately

**Comment by pengcong06** [comment]
**造成unreachable的原因:**
openpitrix在部署的时候将几个k8s service合并到了一个sevice,导致service name发生变化
代码里边是通过service name来访问其他服务,所以产生了找不到service的问题
**解决方案:**
还是按照原来的方案将k8s service分开部署
**解决方案带来的一些问题:**
现在在部署openpitrix的时候是将多个container放在了一个pod里边,同一个pod里边的container之间是可以互相直接访问的,没有必要通过service来访问,所以,决定在pod里边增加hostAliases来简化(不通过k8s service机制)通过service name互相访问的问题;
**k8s service仍需分开部署:**
我们没办法在需要访问openpitrix service的pod里边设置hostAliase,所以其他pod仍需要通过service机制来访问openpitrix service服务

**Comment by zheng1** [comment]
Service可以创建多个, 都绑定到同一个Pod (hyperpitrix)上
