### ISSUE TITLE
Missing client id

### ISSUE THREAD

**Issue by fleeto** [openpitrix/openpitrix#962]
Kubernetes 1.15.5
openpitrix: 0.4.1

![image](https://user-images.githubusercontent.com/6958477/67260005-8a756a80-f4cb-11e9-8370-ad26c3147697.png)

**Comment by zheng1** [comment]
你好，请问使用那种方式进行安装的？如果在kubesphere的基础上安装，请将openpitrix安装在`openpitrix-system`之外的其他namespace上。

**Comment by fleeto** [comment]
就是普通的 Kubernetes，是 OSX 的兼容性问题，已经 PR 了
